language: go

os:
  - linux
  - osx
  - windows

go:
  - "1.x"
  - "1.8"
  - "1.10.x"
  - "1.11.x"
before_install:
  - go get -t -v ./...

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic
  - go build
  
after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: releases
  api_key: ${GITHUB_API_KEY}
  file_glob: true
  file: "image2ascii*"
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
